In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  # library for data analysis for text files (everything but netcdf files)
%matplotlib inline 

In [12]:
## python gotcha #1 -- indexing
foo=np.linspace(0,10,11)

## python is 0 based
print(foo[0])
## indexing over the first 5 values of an array only selects the first 4 values of an array
print(foo[0:4])

0.0
[0. 1. 2. 3.]


In [13]:
## python gotcha #2 -- copying vs. linking arrays

## if you want to copy an array
foo_new = foo.copy() 

## if you want to link an array
foo_new_linked = foo

foo[0]=10
print(foo)
print(foo_new)
print(foo_new_linked)

[10.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
